version: '2'

services:
    #  gateway:
      #    image: c2-elasticsearch:2.4\
      #build: .
      #environment:
      #  UNICAST_HOSTS: master
      #  TYPE: GATEWAY
      #    ports:
      #      - "9200:9200"
      #      - "9300:9300"
  es:
      #    image: c2-elasticsearch:2.4
    build: .
    volumes:
      - .data/data/:/usr/share/elasticsearch/data/
      - .data/logs/:/usr/share/elasticsearch/logs/
      - ./config:/usr/share/elasticsearch/config
    command: elasticsearch 
    ports: 
        - "9200:9200"
        - "9300:9300"

