version: '2'

services:
  gateway:
      #    image: c2-elasticsearch:2.4\
    build: .
    environment:
      UNICAST_HOSTS: master
      TYPE: GATEWAY
    ports:
      - "9200:9200"
      - "9300:9300"

  master:
      #image: c2-elasticsearch:2.4
    build: .
    environment:
      UNICAST_HOSTS: gateway
      TYPE: MASTER
      MIN_MASTERS: 2

  data:
      #    image: c2-elasticsearch:2.4
    build: .
    environment:
      UNICAST_HOSTS: master,gateway
      TYPE: DATA

